package services

import (
	"fmt"
	"log"
	"time"

	"github.com/smart-payment-infrastructure/internal/models"
	"github.com/smart-payment-infrastructure/internal/repository"
	"github.com/smart-payment-infrastructure/pkg/xrpl"
)

// EnhancedXRPLService provides enhanced XRPL functionality using the real XRPL client
type EnhancedXRPLService struct {
	client      *xrpl.EnhancedClient
	initialized bool
}

// Verify that EnhancedXRPLService implements repository.XRPLServiceInterface
var _ repository.XRPLServiceInterface = (*EnhancedXRPLService)(nil)

// NewEnhancedXRPLService creates a new enhanced XRPL service
func NewEnhancedXRPLService(config XRPLConfig) *EnhancedXRPLService {
	client := xrpl.NewEnhancedClient(config.NetworkURL, config.TestNet)
	return &EnhancedXRPLService{
		client: client,
	}
}

// Initialize initializes the enhanced XRPL service
func (s *EnhancedXRPLService) Initialize() error {
	if err := s.client.Connect(); err != nil {
		return fmt.Errorf("failed to connect to XRPL: %w", err)
	}

	if err := s.client.HealthCheck(); err != nil {
		return fmt.Errorf("XRPL health check failed: %w", err)
	}

	s.initialized = true
	log.Println("Enhanced XRPL service initialized successfully")
	return nil
}

// CreateWallet creates a new XRPL wallet using Ed25519 (recommended)
func (s *EnhancedXRPLService) CreateWallet() (*xrpl.WalletInfo, error) {
	if !s.initialized {
		return nil, fmt.Errorf("service not initialized")
	}

	wallet, err := s.client.GenerateWallet()
	if err != nil {
		return nil, fmt.Errorf("failed to create wallet: %w", err)
	}

	log.Printf("Created new XRPL wallet: %s", wallet.Address)
	return wallet, nil
}

// CreateSecp256k1Wallet creates a new XRPL wallet using secp256k1
func (s *EnhancedXRPLService) CreateSecp256k1Wallet() (*xrpl.WalletInfo, error) {
	if !s.initialized {
		return nil, fmt.Errorf("service not initialized")
	}

	wallet, err := s.client.GenerateSecp256k1Wallet()
	if err != nil {
		return nil, fmt.Errorf("failed to create secp256k1 wallet: %w", err)
	}

	log.Printf("Created new XRPL secp256k1 wallet: %s", wallet.Address)
	return wallet, nil
}

// ValidateAddress validates an XRPL address
func (s *EnhancedXRPLService) ValidateAddress(address string) bool {
	return s.client.ValidateAddress(address)
}

// ValidateGeneratedAddress validates an address generated by our system
func (s *EnhancedXRPLService) ValidateGeneratedAddress(address string) bool {
	return s.client.ValidateGeneratedAddress(address)
}

// GetAccountInfo retrieves account information from XRPL
func (s *EnhancedXRPLService) GetAccountInfo(address string) (interface{}, error) {
	if !s.initialized {
		return nil, fmt.Errorf("service not initialized")
	}

	accountInfo, err := s.client.GetAccountInfo(address)
	if err != nil {
		return nil, fmt.Errorf("failed to get account info for %s: %w", address, err)
	}

	return accountInfo, nil
}

// GetAccountBalance retrieves account balance from XRPL
func (s *EnhancedXRPLService) GetAccountBalance(address string) (string, error) {
	if !s.initialized {
		return "", fmt.Errorf("service not initialized")
	}

	balance, err := s.client.GetAccountBalance(address)
	if err != nil {
		return "", fmt.Errorf("failed to get account balance for %s: %w", address, err)
	}

	return balance, nil
}

// HealthCheck performs health check on the XRPL service
func (s *EnhancedXRPLService) HealthCheck() error {
	if !s.initialized {
		return fmt.Errorf("XRPL service not initialized")
	}
	return s.client.HealthCheck()
}

// CreateSmartChequeEscrow creates an escrow for a Smart Check with enhanced milestone support
func (s *EnhancedXRPLService) CreateSmartChequeEscrow(payerAddress, payeeAddress string, amount float64, currency string, milestoneSecret string) (*xrpl.TransactionResult, string, error) {
	if !s.initialized {
		return nil, "", fmt.Errorf("XRPL service not initialized")
	}

	// Convert amount to appropriate format for XRPL
	amountStr := s.client.FormatAmount(amount, currency)

	// Generate condition and fulfillment for milestone completion
	condition, fulfillment, err := s.client.GenerateCondition(milestoneSecret)
	if err != nil {
		return nil, "", fmt.Errorf("failed to generate escrow condition: %w", err)
	}

	// Set escrow parameters
	escrow := &xrpl.EscrowCreate{
		Account:     payerAddress,
		Destination: payeeAddress,
		Amount:      amountStr,
		Condition:   condition,
		// Set cancel after 30 days (approximate ledger time)
		CancelAfter: s.client.GetLedgerTimeOffset(30 * 24 * time.Hour),
	}

	// Create escrow on XRPL
	result, err := s.client.CreateEscrow(escrow)
	if err != nil {
		return nil, "", fmt.Errorf("failed to create escrow on XRPL: %w", err)
	}

	log.Printf("Created Smart Cheque escrow: %s -> %s, Amount: %s, TxID: %s",
		payerAddress, payeeAddress, amountStr, result.TransactionID)

	return result, fulfillment, nil
}

// CreateSmartChequeEscrowWithMilestones creates an escrow with multiple milestones
func (s *EnhancedXRPLService) CreateSmartChequeEscrowWithMilestones(payerAddress, payeeAddress string, amount float64, currency string, milestones []models.Milestone) (*xrpl.TransactionResult, string, error) {
	// For now, use the single milestone implementation
	// In production, this would create a more complex escrow structure
	milestoneSecret := fmt.Sprintf("milestone_%d_%s", time.Now().Unix(), payeeAddress)
	return s.CreateSmartChequeEscrow(payerAddress, payeeAddress, amount, currency, milestoneSecret)
}

// CompleteSmartChequeMilestone completes a milestone in a Smart Cheque escrow
func (s *EnhancedXRPLService) CompleteSmartChequeMilestone(payeeAddress, ownerAddress string, sequence uint32, condition, fulfillment string) (*xrpl.TransactionResult, error) {
	if !s.initialized {
		return nil, fmt.Errorf("XRPL service not initialized")
	}

	// Set escrow finish parameters
	escrowFinish := &xrpl.EscrowFinish{
		Account:       payeeAddress,
		Owner:         ownerAddress,
		OfferSequence: sequence,
		Condition:     condition,
		Fulfillment:   fulfillment,
	}

	// Finish escrow on XRPL
	result, err := s.client.FinishEscrow(escrowFinish)
	if err != nil {
		return nil, fmt.Errorf("failed to finish escrow on XRPL: %w", err)
	}

	log.Printf("Completed Smart Cheque milestone: Account: %s, Owner: %s, Sequence: %d, TxID: %s",
		payeeAddress, ownerAddress, sequence, result.TransactionID)

	return result, nil
}

// CancelSmartCheque cancels a Smart Cheque escrow
func (s *EnhancedXRPLService) CancelSmartCheque(accountAddress, ownerAddress string, sequence uint32) (*xrpl.TransactionResult, error) {
	if !s.initialized {
		return nil, fmt.Errorf("XRPL service not initialized")
	}

	// Set escrow cancel parameters
	escrowCancel := &xrpl.EscrowCancel{
		Account:       accountAddress,
		Owner:         ownerAddress,
		OfferSequence: sequence,
	}

	// Cancel escrow on XRPL
	result, err := s.client.CancelEscrow(escrowCancel)
	if err != nil {
		return nil, fmt.Errorf("failed to cancel escrow on XRPL: %w", err)
	}

	log.Printf("Canceled Smart Cheque escrow: Account: %s, Owner: %s, Sequence: %d, TxID: %s",
		accountAddress, ownerAddress, sequence, result.TransactionID)

	return result, nil
}

// GetEscrowStatus retrieves escrow status from XRPL
func (s *EnhancedXRPLService) GetEscrowStatus(ownerAddress string, sequence string) (*xrpl.EscrowInfo, error) {
	if !s.initialized {
		return nil, fmt.Errorf("XRPL service not initialized")
	}

	// This would typically use XRPL account_tx or account_objects API
	// For now, return mock result as placeholder
	log.Printf("Retrieved escrow status for owner: %s, sequence: %s", ownerAddress, sequence)

	// Return mock escrow info
	escrowInfo := &xrpl.EscrowInfo{
		Account:   ownerAddress,
		Sequence:  uint32(0), // Would be parsed from sequence string
		Amount:    "0",
		Condition: "",
		Flags:     0,
	}

	return escrowInfo, nil
}

// GenerateCondition generates escrow condition and fulfillment
func (s *EnhancedXRPLService) GenerateCondition(secret string) (string, string, error) {
	if !s.initialized {
		return "", "", fmt.Errorf("XRPL service not initialized")
	}

	return s.client.GenerateCondition(secret)
}

// CreatePaymentChannel creates a payment channel for streaming payments
func (s *EnhancedXRPLService) CreatePaymentChannel(sourceAddress, destinationAddress string, amount float64, settleDelay uint32) (*xrpl.TransactionResult, error) {
	if !s.initialized {
		return nil, fmt.Errorf("XRPL service not initialized")
	}

	// Convert amount to drops for XRP
	amountStr := s.client.FormatAmount(amount, "XRP")

	// Create payment channel (simplified - in production, use proper XRPL payment channel creation)
	log.Printf("Creating payment channel: %s -> %s, Amount: %s, SettleDelay: %d",
		sourceAddress, destinationAddress, amountStr, settleDelay)

	// Return mock result for now
	result := &xrpl.TransactionResult{
		TransactionID: "pc_" + fmt.Sprintf("%d", time.Now().Unix()),
		ResultCode:    "tesSUCCESS",
		ResultMessage: "Payment channel created successfully",
	}

	return result, nil
}

// CreateTrustLine creates a trust line for token operations
func (s *EnhancedXRPLService) CreateTrustLine(accountAddress, currency, issuer string, limit string) (*xrpl.TransactionResult, error) {
	if !s.initialized {
		return nil, fmt.Errorf("XRPL service not initialized")
	}

	log.Printf("Creating trust line: Account: %s, Currency: %s, Issuer: %s, Limit: %s",
		accountAddress, currency, issuer, limit)

	// Return mock result for now
	result := &xrpl.TransactionResult{
		TransactionID: "tl_" + fmt.Sprintf("%d", time.Now().Unix()),
		ResultCode:    "tesSUCCESS",
		ResultMessage: "Trust line created successfully",
	}

	return result, nil
}

// Disconnect closes the XRPL service connections
func (s *EnhancedXRPLService) Disconnect() error {
	if s.client != nil {
		return s.client.Disconnect()
	}
	return nil
}
